server:
  port : 7788

debug: true

spring:
#  数据库默认配置
  datasource:
    url : jdbc:mysql://localhost:3306/tom-java?autoconnection&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username : root
    password : 123
    driver-class-name : com.mysql.jdbc.Driver
    type : com.alibaba.druid.pool.DruidDataSource

  #thymeleaf 模板配置
  thymeleaf:
    cache: false #开发阶段，建议关闭Thymeleaf的缓存
    mode: LEGACYHTML5 #使用遗留的html5以去掉对html标签的校验

  application:
    name : tom-web-api

  #mvc配置
  mvc:
    throw-exception-if-no-handler-found: true

  #不开启默认的资源处理
  resources:
    add-mappings: false

  #redis配置
  redis:
    database : 5
    host : 192.168.1.37
    port : 6379
    password : tongtongmallredis
    timeout : 1000
    expiration : 600
  #热部署
  thymeleaf:
    cache : false

#mybatis-plus配置
mybatis-plus:
  mapper-locations : classpath*:com/tom/dao/**/*.xml
  typeAliasesPackage : com.tom.model
  global-config :
    id-type : 2
    field-strategy : 2
    db-column-underline : true
    refresh-mapper : true
    logic-delete-value : 0
  configuration :
    map-underscore-to-camel-case : true
    cache-enabled : false

logging:
  config: classpath:logging/logback-spring-boot.xml


#系统根据业务自定义的一些配置
tom:
  shiro:
    session:
      #seconds
      expire: 12000
